feat: 新增直接提交代码至lc功能
leetcode-pp/leetcode-pp pull request #2
Opened 2021-05-27 00:38 UTC by threedayAAAAA

2021-05-27 02:49 UTC, azl397985856 requested changes
需要二次修改

2021-05-27 02:49 UTC, azl397985856 commented on src/views/91/91algo.vue
> +        url: '/submitLcAccount',
url 命名不规范

2021-05-27 02:49 UTC, azl397985856 commented on src/views/91/91algo.vue
> +      // 1. url与题目数据是写死的，这里的url实际上需要获取当日的最新题目数据进行拼接
url 可以取取接口中的数据
语言可以搞个下拉

2021-05-27 02:49 UTC, azl397985856 commented on src/views/91/91algo.vue
> +      pay: true, // 是否为付费用户
false

2021-05-27 02:49 UTC, azl397985856 commented on src/views/Code.vue
> +  <div class="code-container" ref="container"></div>
文件目录结构不对

2021-05-27 02:49 UTC, azl397985856 commented on src/views/Code.vue
> +      language: 'java',
建议通过 props 传递。 不过你可以搞默认值罢了

2021-05-29 13:30 UTC, threedayAAAAA commented on src/views/91/91algo.vue
> +        url: '/submitLcAccount',
fixed

2021-05-29 13:30 UTC, threedayAAAAA commented on src/views/91/91algo.vue
> +      // 1. url与题目数据是写死的，这里的url实际上需要获取当日的最新题目数据进行拼接
fixed

2021-05-29 13:30 UTC, threedayAAAAA commented on src/views/91/91algo.vue
> +      pay: true, // 是否为付费用户
fixed

2021-05-29 13:30 UTC, threedayAAAAA commented on src/views/Code.vue
> +  <div class="code-container" ref="container"></div>
fixed

2021-05-29 13:30 UTC, threedayAAAAA commented on src/views/Code.vue
> +      language: 'java',
fixed

2021-06-07 08:50 UTC, azl397985856 requested changes

2021-06-07 08:50 UTC, azl397985856 commented on src/views/91/91algo.vue
> +      const data = arr.reduce((obj, key) => {
这里是永远有效的，建议设置一个超时时间。 参考： https://github.com/leetcode-pp/leetcode-pp/blob/d6947d2e3f201dda688b8cf04f79e76c18c1b558/src/apis/request.js#L28

2021-06-12 14:07 UTC, merged